<?php
return [
    ['name' => 'asset.assets.index', 'display_name' => 'View Assets', 'module' => 'Asset'],
    ['name' => 'asset.assets.create', 'display_name' => 'Create Assets', 'module' => 'Asset'],
    ['name' => 'asset.assets.edit', 'display_name' => 'Edit Assets', 'module' => 'Asset'],
    ['name' => 'asset.assets.destroy', 'display_name' => 'Delete Assets', 'module' => 'Asset'],
    ['name' => 'asset.assets.types.index', 'display_name' => 'View Asset Types', 'module' => 'Asset'],
    ['name' => 'asset.assets.types.create', 'display_name' => 'Create Asset Types', 'module' => 'Asset'],
    ['name' => 'asset.assets.types.edit', 'display_name' => 'Edit Asset Types', 'module' => 'Asset'],
    ['name' => 'asset.assets.types.destroy', 'display_name' => 'Delete Asset Types', 'module' => 'Asset'],
    ['name' => 'asset.assets.notes.index', 'display_name' => 'View Asset Notes', 'module' => 'Asset'],
    ['name' => 'asset.assets.notes.create', 'display_name' => 'Create Asset Notes', 'module' => 'Asset'],
    ['name' => 'asset.assets.notes.edit', 'display_name' => 'Edit Asset Notes', 'module' => 'Asset'],
    ['name' => 'asset.assets.notes.destroy', 'display_name' => 'Delete Asset Notes', 'module' => 'Asset'],
    ['name' => 'asset.assets.maintenance.index', 'display_name' => 'View Asset Maintenance', 'module' => 'Asset'],
    ['name' => 'asset.assets.maintenance.create', 'display_name' => 'Create Asset Maintenance', 'module' => 'Asset'],
    ['name' => 'asset.assets.maintenance.edit', 'display_name' => 'Edit Asset Maintenance', 'module' => 'Asset'],
    ['name' => 'asset.assets.maintenance.destroy', 'display_name' => 'Delete Asset Maintenance', 'module' => 'Asset'],
    ['name' => 'asset.assets.files.index', 'display_name' => 'View Asset Files', 'module' => 'Asset'],
    ['name' => 'asset.assets.files.create', 'display_name' => 'Create Asset Files', 'module' => 'Asset'],
    ['name' => 'asset.assets.files.edit', 'display_name' => 'Edit Asset Files', 'module' => 'Asset'],
    ['name' => 'asset.assets.files.destroy', 'display_name' => 'Delete Asset Files', 'module' => 'Asset'],
    ['name' => 'asset.assets.pictures.index', 'display_name' => 'View Asset Pictures', 'module' => 'Asset'],
    ['name' => 'asset.assets.pictures.create', 'display_name' => 'Create Asset Pictures', 'module' => 'Asset'],
    ['name' => 'asset.assets.pictures.edit', 'display_name' => 'Edit Asset Pictures', 'module' => 'Asset'],
    ['name' => 'asset.assets.pictures.destroy', 'display_name' => 'Delete Asset Pictures', 'module' => 'Asset'],
    ['name' => 'asset.assets.valuations.index', 'display_name' => 'View Asset Valuations', 'module' => 'Asset'],
    ['name' => 'asset.assets.valuations.create', 'display_name' => 'Create Asset Valuations', 'module' => 'Asset'],
    ['name' => 'asset.assets.valuations.edit', 'display_name' => 'Edit Asset Valuations', 'module' => 'Asset'],
    ['name' => 'asset.assets.valuations.destroy', 'display_name' => 'Delete Asset Valuations', 'module' => 'Asset'],
];