<?php
/**
 * Created by PhpStorm.
 * User: tj
 * Date: 7/9/19
 * Time: 4:29 PM
 */
return [
    ['name' => 'client.clients.index', 'display_name' => 'View Clients', 'module' => 'Client'],
    ['name' => 'client.clients.index_own', 'display_name' => 'View Own Clients Only', 'module' => 'Client'],
    ['name' => 'client.clients.create', 'display_name' => 'Create Clients', 'module' => 'Client'],
    ['name' => 'client.clients.edit', 'display_name' => 'Edit Clients', 'module' => 'Client'],
    ['name' => 'client.clients.edit_own', 'display_name' => 'Edit Own Clients', 'module' => 'Client'],
    ['name' => 'client.clients.activate', 'display_name' => 'Activate Clients', 'module' => 'Client'],
    ['name' => 'client.clients.activate_own', 'display_name' => 'Activate Own Clients', 'module' => 'Client'],
    ['name' => 'client.clients.destroy', 'display_name' => 'Delete Clients', 'module' => 'Client'],
    ['name' => 'client.clients.destroy_own', 'display_name' => 'Delete Own Clients', 'module' => 'Client'],
    ['name' => 'client.clients.user.create', 'display_name' => 'Create Client Users', 'module' => 'Client'],
    ['name' => 'client.clients.user.destroy', 'display_name' => 'Delete Client Users', 'module' => 'Client'],
    ['name' => 'client.clients.titles.index', 'display_name' => 'View Titles', 'module' => 'Client'],
    ['name' => 'client.clients.titles.create', 'display_name' => 'Create Titles', 'module' => 'Client'],
    ['name' => 'client.clients.titles.edit', 'display_name' => 'Edit Titles', 'module' => 'Client'],
    ['name' => 'client.clients.titles.destroy', 'display_name' => 'Delete Titles', 'module' => 'Client'],
    ['name' => 'client.clients.professions.index', 'display_name' => 'View Professions', 'module' => 'Client'],
    ['name' => 'client.clients.professions.create', 'display_name' => 'Create Professions', 'module' => 'Client'],
    ['name' => 'client.clients.professions.edit', 'display_name' => 'Edit Professions', 'module' => 'Client'],
    ['name' => 'client.clients.professions.destroy', 'display_name' => 'Delete Professions', 'module' => 'Client'],
    ['name' => 'client.clients.client_relationships.index', 'display_name' => 'View Client Relationships', 'module' => 'Client'],
    ['name' => 'client.clients.client_relationships.create', 'display_name' => 'Create Client Relationships', 'module' => 'Client'],
    ['name' => 'client.clients.client_relationships.edit', 'display_name' => 'Edit Client Relationships', 'module' => 'Client'],
    ['name' => 'client.clients.client_relationships.destroy', 'display_name' => 'Delete Client Relationships', 'module' => 'Client'],
    ['name' => 'client.clients.client_types.index', 'display_name' => 'View Client Types', 'module' => 'Client'],
    ['name' => 'client.clients.client_types.create', 'display_name' => 'Create Client Types', 'module' => 'Client'],
    ['name' => 'client.clients.client_types.edit', 'display_name' => 'Edit Client Types', 'module' => 'Client'],
    ['name' => 'client.clients.client_types.destroy', 'display_name' => 'Delete Client Types', 'module' => 'Client'],
    ['name' => 'client.clients.identification_types.index', 'display_name' => 'View Identification Types', 'module' => 'Client'],
    ['name' => 'client.clients.identification_types.create', 'display_name' => 'Create Identification Types', 'module' => 'Client'],
    ['name' => 'client.clients.identification_types.edit', 'display_name' => 'Edit Identification Types', 'module' => 'Client'],
    ['name' => 'client.clients.identification_types.destroy', 'display_name' => 'Delete Identification Types', 'module' => 'Client'],
    ['name' => 'client.clients.files.index', 'display_name' => 'View Files', 'module' => 'Client'],
    ['name' => 'client.clients.files.create', 'display_name' => 'Create Files', 'module' => 'Client'],
    ['name' => 'client.clients.files.edit', 'display_name' => 'Edit Files', 'module' => 'Client'],
    ['name' => 'client.clients.files.destroy', 'display_name' => 'Delete Files', 'module' => 'Client'],
    ['name' => 'client.clients.next_of_kin.index', 'display_name' => 'View Next of kin', 'module' => 'Client'],
    ['name' => 'client.clients.next_of_kin.create', 'display_name' => 'Create Next of kin', 'module' => 'Client'],
    ['name' => 'client.clients.next_of_kin.edit', 'display_name' => 'Edit Next of kin', 'module' => 'Client'],
    ['name' => 'client.clients.next_of_kin.destroy', 'display_name' => 'Delete Next of kins', 'module' => 'Client'],
    ['name' => 'client.clients.identification.index', 'display_name' => 'View Identification', 'module' => 'Client'],
    ['name' => 'client.clients.identification.create', 'display_name' => 'Create Identification', 'module' => 'Client'],
    ['name' => 'client.clients.identification.edit', 'display_name' => 'Edit Identification', 'module' => 'Client'],
    ['name' => 'client.clients.identification.destroy', 'display_name' => 'Delete Identification', 'module' => 'Client'],
    ['name' => 'client.clients.groups.index', 'display_name' => 'View Groups', 'module' => 'Client'],
];