<?php

return [
    ['name' => 'loan.loans.index', 'display_name' => 'View Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.create', 'display_name' => 'Create Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.edit', 'display_name' => 'Edit Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.destroy', 'display_name' => 'Delete Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.approve_loan', 'display_name' => 'Approve/Reject Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.disburse_loan', 'display_name' => 'Disburse Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.withdraw_loan', 'display_name' => 'Withdraw Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.write_off_loan', 'display_name' => 'Write Off Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.reschedule_loan', 'display_name' => 'Reschedule Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.close_loan', 'display_name' => 'Close Loans', 'module' => 'Loan'],
    ['name' => 'loan.loans.calculator', 'display_name' => 'Use Loan Calculator', 'module' => 'Loan'],
    ['name' => 'loan.loans.loan_history', 'display_name' => 'View Loan History', 'module' => 'Loan'],
    ['name' => 'loan.loans.products.index', 'display_name' => 'View Loan Products', 'module' => 'Loan'],
    ['name' => 'loan.loans.products.create', 'display_name' => 'Create Loan Products', 'module' => 'Loan'],
    ['name' => 'loan.loans.products.edit', 'display_name' => 'Edit Loan Products', 'module' => 'Loan'],
    ['name' => 'loan.loans.products.destroy', 'display_name' => 'Delete Loan Products', 'module' => 'Loan'],
    ['name' => 'loan.loans.transactions.index', 'display_name' => 'View Transactions', 'module' => 'Loan'],
    ['name' => 'loan.loans.transactions.create', 'display_name' => 'Create Transactions', 'module' => 'Loan'],
    ['name' => 'loan.loans.transactions.edit', 'display_name' => 'Edit Transactions', 'module' => 'Loan'],
    ['name' => 'loan.loans.transactions.destroy', 'display_name' => 'Delete/Reverse Transactions', 'module' => 'Loan'],
    ['name' => 'loan.loans.charges.index', 'display_name' => 'View Charges', 'module' => 'Loan'],
    ['name' => 'loan.loans.charges.create', 'display_name' => 'Create Charges', 'module' => 'Loan'],
    ['name' => 'loan.loans.charges.edit', 'display_name' => 'Edit Charges', 'module' => 'Loan'],
    ['name' => 'loan.loans.charges.destroy', 'display_name' => 'Delete Charges', 'module' => 'Loan'],
    ['name' => 'loan.loans.funds.index', 'display_name' => 'View Funds', 'module' => 'Loan'],
    ['name' => 'loan.loans.funds.create', 'display_name' => 'Create Funds', 'module' => 'Loan'],
    ['name' => 'loan.loans.funds.edit', 'display_name' => 'Edit Funds', 'module' => 'Loan'],
    ['name' => 'loan.loans.funds.destroy', 'display_name' => 'Delete Funds', 'module' => 'Loan'],
    ['name' => 'loan.loans.credit_checks.index', 'display_name' => 'View Credit Checks', 'module' => 'Loan'],
    ['name' => 'loan.loans.credit_checks.create', 'display_name' => 'Create Credit Checks', 'module' => 'Loan'],
    ['name' => 'loan.loans.credit_checks.edit', 'display_name' => 'Edit Credit Checks', 'module' => 'Loan'],
    ['name' => 'loan.loans.credit_checks.destroy', 'display_name' => 'Delete Credit Checks', 'module' => 'Loan'],
    ['name' => 'loan.loans.collateral.index', 'display_name' => 'View Collateral', 'module' => 'Loan'],
    ['name' => 'loan.loans.collateral.create', 'display_name' => 'Create Collateral', 'module' => 'Loan'],
    ['name' => 'loan.loans.collateral.edit', 'display_name' => 'Edit Collateral', 'module' => 'Loan'],
    ['name' => 'loan.loans.collateral.destroy', 'display_name' => 'Delete Collateral', 'module' => 'Loan'],
    ['name' => 'loan.loans.collateral_types.index', 'display_name' => 'View Collateral Types', 'module' => 'Loan'],
    ['name' => 'loan.loans.collateral_types.create', 'display_name' => 'Create Collateral Types', 'module' => 'Loan'],
    ['name' => 'loan.loans.collateral_types.edit', 'display_name' => 'Edit Collateral Types', 'module' => 'Loan'],
    ['name' => 'loan.loans.collateral_types.destroy', 'display_name' => 'Delete Collateral Types', 'module' => 'Loan'],
    ['name' => 'loan.loans.purposes.index', 'display_name' => 'View Purposes', 'module' => 'Loan'],
    ['name' => 'loan.loans.purposes.create', 'display_name' => 'Create Purposes', 'module' => 'Loan'],
    ['name' => 'loan.loans.purposes.edit', 'display_name' => 'Edit Purposes', 'module' => 'Loan'],
    ['name' => 'loan.loans.purposes.destroy', 'display_name' => 'Delete Purposes', 'module' => 'Loan'],
    ['name' => 'loan.loans.files.index', 'display_name' => 'View Files', 'module' => 'Loan'],
    ['name' => 'loan.loans.files.create', 'display_name' => 'Create Files', 'module' => 'Loan'],
    ['name' => 'loan.loans.files.edit', 'display_name' => 'Edit Files', 'module' => 'Loan'],
    ['name' => 'loan.loans.files.destroy', 'display_name' => 'Delete Files', 'module' => 'Loan'],
    ['name' => 'loan.loans.guarantors.index', 'display_name' => 'View Guarantors', 'module' => 'Loan'],
    ['name' => 'loan.loans.guarantors.create', 'display_name' => 'Create Guarantors', 'module' => 'Loan'],
    ['name' => 'loan.loans.guarantors.edit', 'display_name' => 'Edit Guarantors', 'module' => 'Loan'],
    ['name' => 'loan.loans.guarantors.destroy', 'display_name' => 'Delete Guarantors', 'module' => 'Loan'],
    ['name' => 'loan.loans.notes.index', 'display_name' => 'View Notes', 'module' => 'Loan'],
    ['name' => 'loan.loans.notes.create', 'display_name' => 'Create Notes', 'module' => 'Loan'],
    ['name' => 'loan.loans.notes.edit', 'display_name' => 'Edit Notes', 'module' => 'Loan'],
    ['name' => 'loan.loans.notes.destroy', 'display_name' => 'Delete Notes', 'module' => 'Loan'],
    ['name' => 'loan.loans.reports.collection_sheet', 'display_name' => 'View Collection Sheet Reports', 'module' => 'Loan'],
    ['name' => 'loan.loans.reports.repayments', 'display_name' => 'View Repayments Report', 'module' => 'Loan'],
    ['name' => 'loan.loans.reports.expected_repayments', 'display_name' => 'View Expected Repayments Report', 'module' => 'Loan'],
    ['name' => 'loan.loans.reports.arrears', 'display_name' => 'View Arrears Reports', 'module' => 'Loan'],
    ['name' => 'loan.loans.reports.disbursements', 'display_name' => 'View Disbursements Report', 'module' => 'Loan'],
];