<?php

return [
    ['name' => 'savings.savings.index', 'display_name' => 'View Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.create', 'display_name' => 'Create Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.edit', 'display_name' => 'Edit Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.destroy', 'display_name' => 'Delete Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.approve_savings', 'display_name' => 'Approve/Reject Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.activate_savings', 'display_name' => 'Activate Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.withdraw_savings', 'display_name' => 'Withdraw Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.inactive_savings', 'display_name' => 'Inactive Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.dormant_savings', 'display_name' => 'Dormant Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.close_savings', 'display_name' => 'Close Savings', 'module' => 'Savings'],
    ['name' => 'savings.savings.products.index', 'display_name' => 'View savings Products', 'module' => 'Savings'],
    ['name' => 'savings.savings.products.create', 'display_name' => 'Create savings Products', 'module' => 'Savings'],
    ['name' => 'savings.savings.products.edit', 'display_name' => 'Edit savings Products', 'module' => 'Savings'],
    ['name' => 'savings.savings.products.destroy', 'display_name' => 'Delete savings Products', 'module' => 'Savings'],
    ['name' => 'savings.savings.transactions.index', 'display_name' => 'View Transactions', 'module' => 'Savings'],
    ['name' => 'savings.savings.transactions.create', 'display_name' => 'Create Transactions', 'module' => 'Savings'],
    ['name' => 'savings.savings.transactions.edit', 'display_name' => 'Edit Transactions', 'module' => 'Savings'],
    ['name' => 'savings.savings.transactions.destroy', 'display_name' => 'Delete/Reverse Transactions', 'module' => 'Savings'],
    ['name' => 'savings.savings.charges.index', 'display_name' => 'View Charges', 'module' => 'Savings'],
    ['name' => 'savings.savings.charges.create', 'display_name' => 'Create Charges', 'module' => 'Savings'],
    ['name' => 'savings.savings.charges.edit', 'display_name' => 'Edit Charges', 'module' => 'Savings'],
    ['name' => 'savings.savings.charges.destroy', 'display_name' => 'Delete Charges', 'module' => 'Savings'],
    ['name' => 'savings.savings.reports.transactions', 'display_name' => 'View Transactions Report', 'module' => 'Savings'],
    ['name' => 'savings.savings.reports.balances', 'display_name' => 'View Balances Report', 'module' => 'Savings'],
    ['name' => 'savings.savings.reports.accounts', 'display_name' => 'View Accounts Report', 'module' => 'Savings'],
];