<?php
return [
    ['name' => 'share.shares.index', 'display_name' => 'View Shares', 'module' => 'Share'],
    ['name' => 'share.shares.create', 'display_name' => 'Create Shares', 'module' => 'Share'],
    ['name' => 'share.shares.edit', 'display_name' => 'Edit Shares', 'module' => 'Share'],
    ['name' => 'share.shares.destroy', 'display_name' => 'Delete Shares', 'module' => 'Share'],
    ['name' => 'share.shares.approve_shares', 'display_name' => 'Approve Shares', 'module' => 'Share'],
    ['name' => 'share.shares.activate_shares', 'display_name' => 'Activate Shares', 'module' => 'Share'],
    ['name' => 'share.shares.close_shares', 'display_name' => 'Close Shares', 'module' => 'Share'],
    ['name' => 'share.shares.products.index', 'display_name' => 'View Share Products', 'module' => 'Share'],
    ['name' => 'share.shares.products.create', 'display_name' => 'Create Share Products', 'module' => 'Share'],
    ['name' => 'share.shares.products.edit', 'display_name' => 'Edit Share Products', 'module' => 'Share'],
    ['name' => 'share.shares.products.destroy', 'display_name' => 'Delete Share Products', 'module' => 'Share'],
    ['name' => 'share.shares.transactions.index', 'display_name' => 'View Transactions', 'module' => 'Share'],
    ['name' => 'share.shares.transactions.create', 'display_name' => 'Create Transactions', 'module' => 'Share'],
    ['name' => 'share.shares.transactions.edit', 'display_name' => 'Edit Transactions', 'module' => 'Share'],
    ['name' => 'share.shares.transactions.destroy', 'display_name' => 'Delete/Reverse Transactions', 'module' => 'Share'],
    ['name' => 'share.shares.notes.index', 'display_name' => 'View Share Notes', 'module' => 'Share'],
    ['name' => 'share.shares.notes.create', 'display_name' => 'Create Share Notes', 'module' => 'Share'],
    ['name' => 'share.shares.notes.edit', 'display_name' => 'Edit Share Notes', 'module' => 'Share'],
    ['name' => 'share.shares.notes.destroy', 'display_name' => 'Delete Share Notes', 'module' => 'Share'],
    ['name' => 'share.shares.charges.index', 'display_name' => 'View Share Charges', 'module' => 'Share'],
    ['name' => 'share.shares.charges.create', 'display_name' => 'Create Share Charges', 'module' => 'Share'],
    ['name' => 'share.shares.charges.edit', 'display_name' => 'Edit Share Charges', 'module' => 'Share'],
    ['name' => 'share.shares.charges.destroy', 'display_name' => 'Delete Share Charges', 'module' => 'Share'],
    ['name' => 'share.shares.files.index', 'display_name' => 'View Share Files', 'module' => 'Share'],
    ['name' => 'share.shares.files.create', 'display_name' => 'Create Share Files', 'module' => 'Share'],
    ['name' => 'share.shares.files.edit', 'display_name' => 'Edit Share Files', 'module' => 'Share'],
    ['name' => 'share.shares.files.destroy', 'display_name' => 'Delete Share Files', 'module' => 'Share'],
];